/*
 * Patient Management Api
 *
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your-email@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mdm

import (
	"github.com/gin-gonic/gin"
)

type MedicalRecordsAPI interface {


    // CreateMedicalRecord Post /api/patients/:patientId/medical-records
    // Creates new medical record for patient 
     CreateMedicalRecord(c *gin.Context)

    // DeleteMedicalRecord Delete /api/patients/:patientId/medical-records/:recordId
    // Deletes specific medical record 
     DeleteMedicalRecord(c *gin.Context)

    // GetPatientMedicalRecords Get /api/patients/:patientId/medical-records
    // Provides all medical records for specific patient 
     GetPatientMedicalRecords(c *gin.Context)

    // UpdateMedicalRecord Put /api/patients/:patientId/medical-records/:recordId
    // Updates specific medical record 
     UpdateMedicalRecord(c *gin.Context)

}