/*
 * Patient Management Api
 *
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your-email@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mdm

import (
	"github.com/gin-gonic/gin"
)

type PatientsAPI interface {


    // CreatePatient Post /api/patients
    // Creates a new patient 
     CreatePatient(c *gin.Context)

    // DeletePatient Delete /api/patients/:patientId
    // Deletes specific patient 
     DeletePatient(c *gin.Context)

    // GetAllPatients Get /api/patients
    // Provides list of all patients 
     GetAllPatients(c *gin.Context)

    // GetPatient Get /api/patients/:patientId
    // Provides details about specific patient 
     GetPatient(c *gin.Context)

    // UpdatePatient Put /api/patients/:patientId
    // Updates specific patient 
     UpdatePatient(c *gin.Context)

}