/*
 * Patient Management Api
 *
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your-email@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mdm

import (
	"time"
)

type MedicalRecord struct {

	// Unique identifier of the medical record
	Id string `json:"id"`

	// Unique identifier of the patient
	PatientId string `json:"patientId"`

	// Date and time of the medical visit
	DateOfVisit time.Time `json:"dateOfVisit"`

	// Primary diagnosis
	Diagnosis string `json:"diagnosis"`

	// List of reported symptoms
	Symptoms []string `json:"symptoms,omitempty"`

	// Prescribed treatment
	Treatment string `json:"treatment,omitempty"`

	// List of prescribed medications
	Medications []Medication `json:"medications,omitempty"`

	// Name of the attending physician
	DoctorName string `json:"doctorName,omitempty"`

	// Additional notes
	Notes string `json:"notes,omitempty"`

	// Date for follow-up appointment
	FollowUpDate string `json:"followUpDate,omitempty"`

	// When the record was created
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// When the record was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
