/*
 * Patient Management Api
 *
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your-email@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mdm

import (
	"time"
)

type Patient struct {

	// Unique identifier of the patient
	Id string `json:"id"`

	// First name of the patient
	FirstName string `json:"firstName"`

	// Last name of the patient
	LastName string `json:"lastName"`

	// Date of birth
	DateOfBirth string `json:"dateOfBirth"`

	// Gender (M - male, F - female, O - other)
	Gender string `json:"gender"`

	// Insurance number (rodné číslo)
	InsuranceNumber string `json:"insuranceNumber"`

	// Blood type
	BloodType string `json:"bloodType,omitempty"`

	// Current patient status
	Status string `json:"status,omitempty"`

	// Patient allergies (free text)
	Allergies string `json:"allergies,omitempty"`

	// General medical notes (free text)
	MedicalNotes string `json:"medicalNotes,omitempty"`

	// When the patient record was created
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// When the patient record was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
