/*
 * Patient Management Api
 *
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your-email@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mdm

type Address struct {

	// Street name and number
	Street string `json:"street,omitempty"`

	// City
	City string `json:"city,omitempty"`

	// Postal code
	PostalCode string `json:"postalCode,omitempty"`

	// Country
	Country string `json:"country,omitempty"`
}
