/*
 * Patient Management Api
 *
 * Patient and Medical Records management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your-email@example.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package mdm

type EmergencyContact struct {

	// Name of emergency contact
	Name string `json:"name,omitempty"`

	// Relationship to patient
	Relationship string `json:"relationship,omitempty"`

	// Phone number of emergency contact
	PhoneNumber string `json:"phoneNumber,omitempty"`
}
